@startuml クロスワードパズルサイト ユースケース図
left to right direction

actor パズル作成者 as Creater
actor パズルプレイヤー as Player

rectangle クロスワードサイト {
    rectangle 編集ページ {
        usecase パズル作成 as createPuzzle
        usecase パズル編集 as editPuzzle
    }

    rectangle プレイページ {
        usecase パズルを解く as playPuzzle
    }

    rectangle DB操作機能 {
        usecase パズル情報の取得 as getPuzzle
        usecase パズル情報の更新 as updatePuzzle
    }
}

Creater -down-> createPuzzle
Creater -down-> editPuzzle
Player -up-> playPuzzle

createPuzzle -down-> updatePuzzle
getPuzzle -up-> editPuzzle
editPuzzle -down-> updatePuzzle
getPuzzle -down-> playPuzzle

@enduml